# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ngiov\OneDrive\Python\SerialConsole\UI.ui'
#
# Created: Mon Dec 28 14:43:07 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(655, 452)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(562, 452))
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(True)
        Form.setStyleSheet("")
        self.gridLayout_5 = QtGui.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CboCOMPorts = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CboCOMPorts.sizePolicy().hasHeightForWidth())
        self.CboCOMPorts.setSizePolicy(sizePolicy)
        self.CboCOMPorts.setObjectName("CboCOMPorts")
        self.gridLayout_4.addWidget(self.CboCOMPorts, 0, 0, 1, 1)
        self.BtnConectar = QtGui.QPushButton(self.groupBox)
        self.BtnConectar.setObjectName("BtnConectar")
        self.gridLayout_4.addWidget(self.BtnConectar, 0, 1, 1, 1)
        self.CboBaudRate = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CboBaudRate.sizePolicy().hasHeightForWidth())
        self.CboBaudRate.setSizePolicy(sizePolicy)
        self.CboBaudRate.setObjectName("CboBaudRate")
        self.gridLayout_4.addWidget(self.CboBaudRate, 1, 0, 1, 1)
        self.BtnDesconectar = QtGui.QPushButton(self.groupBox)
        self.BtnDesconectar.setObjectName("BtnDesconectar")
        self.gridLayout_4.addWidget(self.BtnDesconectar, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.TxtEnviar = QtGui.QLineEdit(self.groupBox_2)
        self.TxtEnviar.setObjectName("TxtEnviar")
        self.horizontalLayout_4.addWidget(self.TxtEnviar)
        self.BtnEnviar = QtGui.QPushButton(self.groupBox_2)
        self.BtnEnviar.setObjectName("BtnEnviar")
        self.horizontalLayout_4.addWidget(self.BtnEnviar)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ChkNuevaLinea = QtGui.QCheckBox(self.groupBox_2)
        self.ChkNuevaLinea.setObjectName("ChkNuevaLinea")
        self.horizontalLayout_3.addWidget(self.ChkNuevaLinea)
        self.ChkRetornoCarro = QtGui.QCheckBox(self.groupBox_2)
        self.ChkRetornoCarro.setObjectName("ChkRetornoCarro")
        self.horizontalLayout_3.addWidget(self.ChkRetornoCarro)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TxtDatosRecibidos = QtGui.QTextEdit(self.groupBox_3)
        self.TxtDatosRecibidos.setObjectName("TxtDatosRecibidos")
        self.gridLayout_3.addWidget(self.TxtDatosRecibidos, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Serial Console", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Conexion", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnConectar.setText(QtGui.QApplication.translate("Form", "Conectar", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnDesconectar.setText(QtGui.QApplication.translate("Form", "Desconectar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Enviar Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnEnviar.setText(QtGui.QApplication.translate("Form", "Enviar", None, QtGui.QApplication.UnicodeUTF8))
        self.ChkNuevaLinea.setText(QtGui.QApplication.translate("Form", "Agregar NL", None, QtGui.QApplication.UnicodeUTF8))
        self.ChkRetornoCarro.setText(QtGui.QApplication.translate("Form", "Agregar RC", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Datos Recibidos", None, QtGui.QApplication.UnicodeUTF8))

